# Generated by Django 4.1 on 2022-12-26 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_delete_profile'),
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '2. Customers'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': '3. Vendors '},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': '4. Profile'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '1. Users'},
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '5. Wishlist',
            },
        ),
    ]
