# Generated by Django 4.1 on 2022-12-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customer_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='event',
            new_name='comic',
        ),
    ]
