# Generated by Django 4.1 on 2022-12-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_event_wishlist_comic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
