# Generated by Django 4.1 on 2022-08-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_banner_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
