# Generated by Django 4.1 on 2022-10-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_banner_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
