# Generated by Django 4.1 on 2022-12-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_user_comic_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='file',
            field=models.FileField(upload_to='comic_files/'),
        ),
    ]
