# Generated by Django 4.1 on 2022-12-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_comic_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=200), max_length=400),
        ),
    ]
