# Generated by Django 4.1 on 2022-12-19 07:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_file_comic_comicbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
