# Generated by Django 4.1 on 2022-12-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_comicreview_options_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
